### ISSUE TITLE
Dead link in translation guide

### ISSUE THREAD

**Issue by LaoshuBaby** [loomio/loomio-docs#13]
In document page https://help.loomio.com/en/user_manual/users/translation/#help-translate-loomio, the "[Loomio Transifex page](https://www.transifex.com/projects/p/loomio-1/)"] will redirect to https://explore.transifex.com/ and can't find the project

I need to search loomio on Transifex and found 2 project: 

![图片](https://github.com/loomio/loomio-docs/assets/42690037/30cc3ec1-603e-47d9-8e68-0dda9b88b676)

---

Related file: https://github.com/loomio/loomio-docs/blob/main/en/src/user_manual/users/translation/index.md

**Comment by robguthrie** [comment]
Thanks for reporting this. Transifex broke their links. I've just updated the documentation.
